#!/bin/sh

DAEMON="dufs"
EXEC="/usr/sbin/$DAEMON"
PIDFILE="/var/run/$DAEMON.pid"

DUFS_ARGS="-A -p 7304 --assets /var/www/assets/ /"

# shellcheck source=/dev/null
[ -r "/etc/default/$DAEMON" ] && . "/etc/default/$DAEMON"

start() {
	printf 'Starting %s: ' "$DAEMON"
	# shellcheck disable=SC2086 # we need the word splitting
	start-stop-daemon -S -b -q -p "$PIDFILE" -x "$EXEC" \
		-- $DUFS_ARGS
	status=$?
	if [ "$status" -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}

stop() {
	printf 'Stopping %s: ' "$DAEMON"
	start-stop-daemon -K -q -p "$PIDFILE" -x "$EXEC"
	status=$?
	if [ "$status" -eq 0 ]; then
		# Give $DAEMON time to send dying gasp to syslog
		sleep 1
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}

restart() {
	stop
	start
}

case "$1" in
	start|stop|restart)
		"$1";;
	reload)
		restart;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
esac
